# 1) build estático do Vite
FROM node:18-alpine AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build   # gera ./dist

# 2) serve com nginx
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
# substitua todo o default.conf pelo seu proxy
COPY nginx.conf /etc/nginx/conf.d/default.conf
